const OPEN_ID_DIALOG = "OPEN_ID_DIALOG";
const CLOSE_ID_DIALOG = "CLOSE_ID_DIALOG";
const TOGGEL_DRAWER = "TOGGEL_DRAWER";
const ONLY_REG_SECTION = "ONLY_REG_SECTION";
const ONLY_VIEW_SECTION = "ONLY_VIEW_SECTION";
const DEFAULT_DASHBOARD_DISPLAY = "  DEFAULT_DASHBOARD_DISPLAY";
const DISPLAY_EDITOR = "DISPALY_EDITOR";
const CLOSE_EDITOR = "CLOSE_EDITOR";

module.exports = {
  OPEN_ID_DIALOG,
  CLOSE_ID_DIALOG,
  TOGGEL_DRAWER,
  ONLY_REG_SECTION,
  ONLY_VIEW_SECTION,
  DEFAULT_DASHBOARD_DISPLAY,
  DISPLAY_EDITOR,
  CLOSE_EDITOR
};
